name: Tests

on:
  - push
  - pull_request

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.9']
    env:
      output: "                       1493    547    63%   ======================== 24 passed, 1 xfailed in 5.54s ========================"

    steps:
      - name: Test with tox (windows)
        if: matrix.os == 'windows-latest'
        run: $env:PYTEST_OUTPUT = "${{env.output}}"
      - name: Test with tox (non-windows)
        if: matrix.os != 'windows-latest'
        run: export PYTEST_OUTPUT="${{env.output}}"

      - name: Coverage Windows Trim
        if: matrix.os == 'windows-latest'
        run: |
          echo "${{env.PYTEST_OUTPUT}}"
          $env:PYTEST_TRIMMED = ${{env.PYTEST_OUTPUT}}.Substring(${{env.PYTEST_OUTPUT}}.Length - 120)
      - name: Coverage Non-Windows Trim
        if: matrix.os != 'windows-latest'
        run: |
          echo "${{env.PYTEST_OUTPUT}}"


      - name: Coverage Windows Clean
        if: matrix.os == 'windows=latest'
        run: |
          echo ${{env.PYTEST_TRIMMED}}
          $env:PERCENTAGE_WIN = ${{env.PYTEST_TRIMMED}} -replace '[\s0-9=]*(?<pattern>[0-9][0-9])%[\s=a-z0-9,.]*', '${pattern}'

      - name: Make badge windows
        if: ( (${{matrix.os}} == "windows-latest") && (${{matrix.python-version}} == '3.9') )
        uses: schneegans/dynamic-badges-action@v1.6.0
        with:
          # GIST_TOKEN is a GitHub personal access token with scope "gist".
          auth: ${{ secrets.GIST_TOKEN }}
          gistID: 4fb351291438ee5d4f772ff9966f06d3   # replace with your real Gist id.
          filename: covbadge_windows.json
          label: Windows
          message: ${{ env.PERCENTAGE_WIN }}%
          minColorRange: 0
          maxColorRange: 100
          valColorRange: ${{ env.PERCENTAGE_WIN }}


