name: Tests

on:
  - push
  - pull_request

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.9']

    steps:

      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox tox-gh-actions

      - name: Normal tox
        run: tox

      - name: Test with tox (windows)
        if: matrix.os == 'windows-latest'
        run: |
          $env:TOX_RAW = $( tox )
          $env:TOX_TRIMMED = $env:TOX_RAW -replace 'TOTAL[\s0-9]*%', '${pattern}'
          $env:TOX_PERC = $env:TOX_TRIMMED -replace '[\s0-9a-zA-Z=]*(?<pattern>[0-9][0-9])%[\s=a-z0-9,.]*', '${pattern}'
          echo " >>>>>>>>>> $TOX_PERC >>>>>>>>>> $TOX_TRIMMED <<<<<<<<<<<<<< $TOX_RAW <<<<<<<<<<<<<<<<<"
          echo "PERCENTAGE_WIN=$env:TOX_PERC" >> $env:GITHUB_ENV
      - name: Test with tox (ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          export TOX_RAW=$( python -m tox )
          export TOX_TRIMMED=$( [[ ${TOX_RAW} =~ (TOTAL[[:blank:]0-9]*%) ]] && echo "${BASH_REMATCH[1]}" )
          export TOX_PERC_WITH_SYMBOL=$( [[ ${TOX_TRIMMED} =~ ([0-9]*%) ]] && echo "${BASH_REMATCH[1]}" )
          export TOX_PERC=$( [[ ${TOX_TRIMMED} =~ ([0-9]*) ]] && echo "${BASH_REMATCH[1]}" )
          echo " >>>>>>>>>> $TOX_PERC >>>>>>>>>>>>> $TOX_PERC_WITH_SYMBOL ||||||||||||||||| $TOX_TRIMMED <<<<<<<<< $TOX_RAW <<<<<<<<<<<<<<<<<"
          echo "PERCENTAGE_UBUNTU=${TOX_PERC}" >> $GITHUB_ENV
      - name: Test with tox (macos)
        if: matrix.os == 'macos-latest'
        run: |
          export TOX_RAW=$( python -m tox )
          export TOX_TRIMMED=$( [[ ${TOX_RAW} =~ (TOTAL[[:blank:]0-9]*%) ]] && echo "${BASH_REMATCH[1]}" )
          export TOX_PERC_WITH_SYMBOL=$( [[ ${TOX_TRIMMED} =~ ([0-9]*%) ]] && echo "${BASH_REMATCH[1]}" )
          export TOX_PERC=$( [[ ${TOX_TRIMMED} =~ ([0-9]*) ]] && echo "${BASH_REMATCH[1]}" )
          echo " >>>>>>>>>> $TOX_PERC >>>>>>>>>>>>> $TOX_PERC_WITH_SYMBOL ||||||||||||||||| $TOX_TRIMMED <<<<<<<<< $TOX_RAW <<<<<<<<<<<<<<<<<"
          echo "PERCENTAGE_MACOS=${TOX_PERC}" >> $GITHUB_ENV
      - name: Output (windows)
        if: matrix.os == 'windows-latest'
        run: |
          echo "${{env.PERCENTAGE_WIN}}"
      - name: Output (ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          echo "${{env.PERCENTAGE_UBUNTU}}"
      - name: Output (macos)
        if: matrix.os == 'macos-latest'
        run: |
          echo "${{env.PERCENTAGE_MACOS}}"
      

      - name: Make badge (windows)
        if: matrix.os == 'windows-latest'
        uses: schneegans/dynamic-badges-action@v1.6.0
        with:
          # GIST_TOKEN is a GitHub personal access token with scope "gist".
          auth: ${{ secrets.GIST_TOKEN }}
          gistID: 4fb351291438ee5d4f772ff9966f06d3   # replace with your real Gist id.
          filename: covbadge_windows.json
          label: Windows
          message: ${{ env.PERCENTAGE_WIN }}%
          minColorRange: 0
          maxColorRange: 100
          valColorRange: ${{ env.PERCENTAGE_WIN }}

      - name: Make badge (ubuntu)
        if: matrix.os == 'ubuntu-latest'
        uses: schneegans/dynamic-badges-action@v1.6.0
        with:
          # GIST_TOKEN is a GitHub personal access token with scope "gist".
          auth: ${{ secrets.GIST_TOKEN }}
          gistID: 4fb351291438ee5d4f772ff9966f06d3   # replace with your real Gist id.
          filename: covbadge_ubuntu.json
          label: Ubuntu
          message: ${{ env.PERCENTAGE_UBUNTU }}%
          minColorRange: 0
          maxColorRange: 100
          valColorRange: ${{ env.PERCENTAGE_UBUNTU }}

      - name: Make badge (macos)
        if: matrix.os == 'macos-latest'
        uses: schneegans/dynamic-badges-action@v1.6.0
        with:
          # GIST_TOKEN is a GitHub personal access token with scope "gist".
          auth: ${{ secrets.GIST_TOKEN }}
          gistID: 4fb351291438ee5d4f772ff9966f06d3   # replace with your real Gist id.
          filename: covbadge_macos.json
          label: MacOSX
          message: ${{ env.PERCENTAGE_MACOS }}%
          minColorRange: 0
          maxColorRange: 100
          valColorRange: ${{ env.PERCENTAGE_MACOS }}